name       : davfs2
version    : 1.6.0
release    : 5
source     :
    - https://de.freedif.org/savannah/davfs2/davfs2-1.6.0.tar.gz : 2e6b675685bd917772be60f0999ae098c80f79ff20dc131e8fec4547cbb63b50
license    : GPL-3.0-or-later
component  : network.util
summary    : A file system driver for WebDAV
description: |
    davfs2 is a Linux file system driver that allows you to mount a WebDAV
    resource into your Unix file system tree. So - and that is what makes
    davfs2 different - applications can use it without knowing about WebDAV.
    You may edit WebDAV resources using standard applications that interact
    with the file system as usual.
builddeps  :
    - pkgconfig(neon)
setup      : |
    %configure sbindir=/sbin dav_localstatedir=/run dav_user=nobody
build      : |
    %make
install    : |
    %make_install

    # Doesn't contain anything useful
    rm -rf $installdir/usr/share/doc

    install -Dm00644 $pkgfiles/davfs2.sysusers $installdir/%libdir%/sysusers.d/davfs2.conf
    install -Dm00644 $pkgfiles/davfs2.tmpfiles $installdir/%libdir%/tmpfiles.d/davfs2.conf
