name       : davfs2
version    : 1.5.6
release    : 4
source     :
    - https://download.savannah.nongnu.org/releases/davfs2/davfs2-1.5.6.tar.gz : 417476cdcfd53966b2dcfaf12455b54f315959b488a89255ab4b44586153d801
license    : GPL-3.0-or-later
component  : network.util
summary    : A file system driver for WebDAV
description: |
    davfs2 is a Linux file system driver that allows you to mount a WebDAV
    resource into your Unix file system tree. So - and that is what makes
    davfs2 different - applications can use it without knowing about WebDAV.
    You may edit WebDAV resources using standard applications that interact
    with the file system as usual.
builddeps  :
    - pkgconfig(neon)
setup      : |
    %configure sbindir=/sbin dav_localstatedir=/run dav_user=nobody
build      : |
    %make
install    : |
    %make_install

    # Doesn't contain anything useful
    rm -rf $installdir/usr/share/doc

    install -Dm00644 $pkgfiles/davfs2.sysusers $installdir/%libdir%/sysusers.d/davfs2.conf
    install -Dm00644 $pkgfiles/davfs2.tmpfiles $installdir/%libdir%/tmpfiles.d/davfs2.conf
